project_id = "ojsntfmlavrjsvstpjbt"

[functions.upload-file]
verify_jwt = false

[functions.download-file]
verify_jwt = false

[functions.create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.process-payment]
verify_jwt = false
