// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojsntfmlavrjsvstpjbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qc250Zm1sYXZyanN2c3RwamJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MjA2MjQsImV4cCI6MjA4Nzk5NjYyNH0.GQzRWkYWJ_Nb5jHrlp0TV_H0i6KuLgWmGGBWOgpt-88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});